name: Deploy majesty-server

on:
  push:
    branches: [ "main" ]
    paths:
    - majesty-server/**
  pull_request:
    branches: [ "main" ]
    paths:
    - majesty-server/**
  workflow_dispatch:

jobs:

  build_push_deploy:
    name: Build, push and deploy majesty-server
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: ${{ github.run_number }}
    steps:
    
    - uses: actions/checkout@v3
      
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: majesty-server
        platforms: linux/arm64
        push: true
        tags: jupiterpi/majesty-server:${{ env.IMAGE_TAG }}
    
    - name: Set image tag
      uses: jacobtomlinson/gha-find-replace@v3
      with:
        find: "jupiterpi/majesty-server"
        replace: "jupiterpi/majesty-server:${{ env.IMAGE_TAG }}"
        include: "majesty-server/kubernetes/**"

    - name: Deploy to Kubernetes
      uses: fjogeleit/http-request-action@v1
      with:
        url: 'http://kube-cd.jupiterpi.de/applyKubernetesResource/majesty-server-githubactions/majesty-server.yaml'
        method: POST
        customHeaders: '{"Authorization": "Bearer ${{ secrets.KUBE_CD_TOKEN }}"}'
        contentType: text/plain
        file: majesty-server/kubernetes/majesty-server.yaml